# Aquameta Configuration



# PostgreSQL connection settings
[Database]
User = "eric"
Password = "whatevz"
Host = "localhost"
Port = 9876
DatabaseName = "aquameta"
RuntimePath = "./postgres"

[User]
Name = "Eric Hanson"
Email = "eric@aquameta.com"

[Webserver]
#  Web server settings
IP = "0.0.0.0"
Port = "4443"
Protocol = "https" # http or https
SSLCertificateFile = "server.crt" # can use absolute or relative paths, relative is relative to current working directory (?)
SSLKeyFile = "server.key"

[Webrtc]
