# Aquameta Configuration



# PostgreSQL connection settings
[Database]
#Connection = "postgres://?path=/var/run/postgresql&database=aquameta"
Connection = "postgres://?database=aquameta"

[Webserver]
#  Web server settings
IP = "0.0.0.0"
Port = 443
Protocol = "https" # http or https
SSLCertificate = "server.crt" # can use absolute or relative paths, relative is relative to current working directory (?)
SSLKey = "server.key"

[Webrtc]
